<!-- BEGIN (write your solution here) -->
<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
  <input type="submit" value="Search" />
</form>

<table>
  <?php foreach ($users as $key => $user) : ?>
    <tr>
      <td>
         <a href="/users/<?= htmlspecialchars($key) ?>"><?= htmlspecialchars($user) ?></a>
      </td>
    </tr>
  <?php endforeach ?>
</table>
<!-- END -->

